name: Bastion Packer
jobs:
- job: Ubuntu1804
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - checkout: self
  - task: AzureCLI@2
    displayName: Test and validate packer syntax
    inputs:
      azureSubscription: dts-management-sbox-intsvc
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        packer validate --syntax-only ubuntu.pkr.hcl

  - task: CmdLine@2
    displayName: Build and publish packer image Prod
    inputs:
      script: |
        packer build ubuntu.pkr.hcl
    env:
      client_id: $(client_id)
      client_secret: $(client_secret)
      tenant_id: $(tenant_id)
      subscription_id: 2b1afc19-5ca9-4796-a56f-574a58670244
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/fixing'))
