name: Bastion Packer
jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self
      - task: riezebosch.Packer.PackerTool.PackerTool@0
        displayName: 'Install Packer'
        inputs:
          version: 1.7.4

      - task: riezebosch.Packer.Packer.Packer@0
        displayName: 'Validate'
        inputs:
          command: validate
          azureSubscription: dts-management-prod-intsvc

      - task: riezebosch.Packer.Packer.Packer@0
        displayName: 'Build'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          command: build
          azureSubscription: dts-management-prod-intsvc
