name: Bastion Packer
jobs:
  - job: Ubuntu1804
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: Test and validate packer syntax
        inputs:
          azureSubscription: dts-management-sbox-intsvc
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            packer validate --syntax-only ubuntu.pkr.hcl

      - task: AzureCLI@2
        displayName: Build and publish packer image Prod
        inputs:
          azureSubscription: dts-management-prod-intsvc
          addSpnToEnvironment: true
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            packer build \
            -var 'client_id=$env:servicePrincipalId' \
            -var 'client_secret=$env:servicePrincipalKey' \
            -var 'tenant_id=$env:tenantId' \
            ubuntu.pkr.hcl
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))