name: DevOps RDO Bastion Packer
jobs:
- job: Ubuntu1804
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - checkout: self
  - task: CmdLine@2
    displayName: Test and validate packer syntax
    inputs:
      script: |
        packer validate --syntax-only ubuntu.json

  - task: CmdLine@2
    displayName: Build and publish packer image Sandbox
    inputs:
      script: |
        packer build ubuntu.json
    env:
      client_id: $(client_id)
      client_secret: $(client_secret)
      tenant_id: $(tenant_id)
      subscription_id: ea3a8c1e-af9d-4108-bc86-a7e2d267f49c
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
    
  - task: CmdLine@2
    displayName: Build and publish packer image NonProd
    inputs:
      script: |
        packer build ubuntu.json
    env:
      client_id: $(client_id)
      client_secret: $(client_secret)
      tenant_id: $(tenant_id)
      subscription_id: fb084706-583f-4c9a-bdab-949aac66ba5c
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: CmdLine@2
    displayName: Build and publish packer image Prod
    inputs:
      script: |
        packer build ubuntu.json
    env:
      client_id: $(client_id)
      client_secret: $(client_secret)
      tenant_id: $(tenant_id)
      subscription_id: 0978315c-75fe-4ada-9d11-1eb5e0e0b214
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))

