name: Bastion Packer
jobs:
  - job: Ubuntu1804
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - checkout: self
      - task: riezebosch.Packer.PackerTool.PackerTool@0
        displayName: 'Install Packer'
        inputs:
          version: 1.7.4

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Validate'
        inputs:
          command: validate
          azureSubscription: dts-management-prod-intsvc

      - task: riezebosch.Packer.Packer.Packer@1
        displayName: 'Build'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/fix-pipeline'))
        inputs:
          command: build
          azureSubscription: dts-management-prod-intsvc