name: Bastion Packer
jobs:
  - job: Ubuntu1804
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: Test and validate packer syntax
        inputs:
          azureSubscription: dts-management-sbox-intsvc
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            packer validate --syntax-only ubuntu.pkr.hcl

      - task: PackerBuild@1
        inputs:
          connectedServiceName: DTS-MANAGEMENT-PROD-INTSVC
          azureResourceGroup: hmcts-image-gallery-rg
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))


