name: DevOps RDO Bastion Packer
jobs:
- job: Ubuntu1804
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - checkout: self

  - task: AzureCLI@2
    displayName: Azure CLI
    inputs:
      azureSubscription: 
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        packer validate --syntax-only ubuntu.json
    env:
      client_id: $(client_id)
      client_secret: $(client_secret)
      tenant_id: $(tenant_id)
      subscription_id: ea3a8c1e-af9d-4108-bc86-a7e2d267f49c